---

- hosts: all
  become: true
  tasks:
    - name: Create NFS share directory
      file:
        path: /mnt/nfsshare
        state: directory
        mode: '0777'

    - name: Install NFS packages
      apt:
        name: nfs-kernel-server
        state: latest

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: '/mnt/nfsshare 192.168.1.0/24(rw,sync,no_root_squash)'
        state: present

    - name: Restart NFS
      service:
        name: nfs-kernel-server
        state: restarted
