---

- name: Create Samba share
  hosts: all
  tasks:
    - name: Install Samba
      package:
        name: samba
        state: present

    - name: Create Samba share directory
      file:
        path: /mnt/sambashare
        state: directory
        mode: 0777

    - name: Add Samba share configuration
      lineinfile:
        path: /etc/samba/smb.conf
        line: |
          [sambashare]
                path = /mnt/sambashare
                read only = no
                browseable = yes
                guest ok = yes
                create mask = 0777
                directory mask = 0777

    - name: restart samba
      systemd:
        service: smb
        state: restarted

    - name: install semanage
      package:
        name: policycoreutils-python-utils
        state: present

    - name: Set new fcontext for file
      sefcontext:
        target: "/mnt/sambashare(/.*)?"
        setype: "samba_share_t"
        state: present

    - name: use restorecon
      raw: restorecon /mnt/sambashare/

    - name: add smb to firewall
      firewalld:
        port: 445/tcp
        permanent: true
        state: enabled
        immediate: yes


